version: "3.2"
services:
  quiz-app:
    image: registry.gitlab.com/karolinawisniewska/dockertest/java/quizapi:v2
    restart: always
    container_name: quiz-app
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://database:3306/quiz?serverTimezone=UTC
    depends_on:
      -   database
    volumes:
      - .m2:/root/.m2

  database:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    container_name:   database
    command: --default-authentication-plugin=mysql_native_password --init-file /data/application/init.sql
    restart: always
    environment:
      MYSQL_DATABASE: quiz
      MYSQL_ROOT_PASSWORD: coderslab
    ports:
      - "3309:3306"
    volumes:
      - mysqldb:/var/lib/mysql
      - ./init/schema.sql:/data/application/init.sql
volumes:
  mysqldb:
    driver: local
