spring:
  datasource:
    url: jdbc:mysql://localhost:3306/quiz?serverTimezone=UTC
    username: root
    password: coderslab
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
quiz-api:
  url: https://quizapi.io/api/v1/questions?apiKey=NQJpUGZ7hs2FpzZuytJiwGvL31eWD010eANEPZEi
  params:
    - name: apiKey
      value: NQJpUGZ7hs2FpzZuytJiwGvL31eWD010eANEPZEi
    - name: limit
      value: 1
