spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:3306/quiz?serverTimezone=UTC
    username: ${USERNAME}
    password: ${PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
quiz-api:
  url: https://quizapi.io/api/v1/questions?apiKey=${API_KEY}&limit=1
  number-of-questions: 10